# Name of the GitHub Actions workflow
name: E2E Tests - Playwright

# When to trigger this workflow:
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e:
    # Use latest Ubuntu VM
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js (v18)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Install Playwright browsers and dependencies
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      # Step 5: Install wait-on (used to wait for the dev server)
      - name: Install wait-on
        run: yarn add -D wait-on

      # Step 6: Start Next.js app in the background & wait for it
      - name: Start dev server
        run: |
          yarn dev &                   # Start dev server in background
          npx wait-on http://localhost:3000 # Wait until it's ready

      # Step 7: Run Playwright tests (headed or headless)
      - name: Run Playwright tests (headless)
        run: yarn playwright test
